version = "1.0"
[main]
name = "Configuration"
    
   [main.comptes]
   name = "Comptes"
        
      [main.comptes.creation_compte]
      ask.en = "Enable account creation"
      ask.fr = "Permettre la création de nouveaux comptes"
      type = "select"
      choices = ["true", "false"]
      default = "true"
      help = "Don't disable account creation before creating one for yourself !"
        
      [main.comptes.connexion_compte]
      ask.en = "Enable account connexion"
      ask.fr = "Permettre la connexion aux comptes"
      type = "select"
      choices = ["true", "false"]
      default = "true"

   [main.export]
   name = "Export"
     
      [main.export.csv_sep]
      ask.en = "Separator for data export in csv format"
      ask.fr = "Séparateur pour l'export des données au format csv"
      type = "string"
      default = ";"
        