version = "1.0"
[main]
name = "Configuration"
services = [ 'php8.3-fpm']
    
   [main.comptes]
   name = "Comptes"
        
      [main.comptes.creation_compte]
      ask.en = "Enable account creation"
      ask.fr = "Permettre la création de nouveaux comptes"
      type = "boolean"
      yes = true
      no = false
      default = true
      help = "Don't disable account creation before creating one for yourself !"
        
      [main.comptes.connexion_compte]
      ask.en = "Enable account connexion"
      ask.fr = "Permettre la connexion aux comptes"
      type = "boolean"
      yes = true
      no = false
      default = true

   [main.export]
   name = "Export"
     
      [main.export.csv_sep]
      ask.en = "Separator for data export in csv format"
      ask.fr = "Séparateur pour l'export des données au format csv"
      type = "string"
      default = ';'

[statistics]
name = "Statistiques"

[statistics.comptes]
name = "Satistiques des comptes"

[statistics.comptes.moncycle_app_nb_compte]
ask.fr = "Nombre de comptes"
type = "number"
readonly = true

[statistics.comptes.moncycle_app_nb_session]
ask.fr = "Nombre de sessions"
type = "number"
readonly = true

[statistics.comptes.moncycle_app_visite_mensuel]
ask.fr = "Nombre de visites mensuelles"
type = "number"
readonly = true

[statistics.comptes.moncycle_app_visite_hebdo]
ask.fr = "Nombre de visites hebdomadaires"
type = "number"
readonly = true

[statistics.comptes.moncycle_app_visite_jour]
ask.fr = "Nombre de visites quotidiennes"
type = "number"
readonly = true

[statistics.comptes.moncycle_app_nb_compte_actif]
ask.fr = "Nombre de comptes actifs"
type = "number"
readonly = true

[statistics.comptes.moncycle_app_pc_compte_actif]
ask.fr = "Pourcentage de comptes actifs"
type = "string"
readonly = true

[statistics.comptes.moncycle_app_nb_compte_avec_totp]
ask.fr = "Nombre de comptes avec totp"
type = "number"
readonly = true

[statistics.comptes.moncycle_app_nb_compte_actif_billings]
ask.fr = "Nombre de comptes Billings actifs"
type = "number"
readonly = true

[statistics.comptes.moncycle_app_pc_compte_actif_billings]
ask.fr = "Pourcentage de comptes actifs Billings"
type = "string"
readonly = true




