version = "1.0"
[main]
    [main.main]
        [main.main.CREATION_COMPTE]
        ask.en = "Création de comptes"
        type = "select"
        choices = ["true", "false"]
        bind = ":__INSTALL_DIR__/config.php"