version = "1.0"
[main]
name = "Moncycle.app configuration"
    
    [main.comptes]
    name = "comptes"
        
        [main.comptes.creation_compte]
        ask.en = "Enable account creation"
        ask.fr = "Permettre la création de nouveaux comptes"
        type = "boolean"
        default = "true"
        yes = "true"
        no = "false"
        help = "Don't disable account creation before creating one for yourself !"
        bind = "CREA_COMPTE:__INSTALL_DIR__/config.php"
        
        [main.comptes.connexion_compte]
        ask.en = "Enable account connexion"
        ask.fr = "Permettre la connexion aux comptes"
        type = "boolean"
        default = "true"
        yes = "true"
        no = "false"
        bind = "CON_COMPTE:__INSTALL_DIR__/config.php"
    
    [main.export]
    name = "export"
        
        [main.export.separateur_csv]
        ask.en = "Separator for data export in csv format"
        ask.fr = "Séparateur pour l'export des données au format csv"
        type = "string"
        default = ";"
        bind = "SEPARATEUR_CSV:__INSTALL_DIR__/config.php"