packaging_format = 2

id = "moncycle"
name = "Moncycle"
description.en = "Menstrual cycle follow-up for natural family planning"
description.fr = "Suivi de cycle pour les méthodes naturelles de régulation de naissance"

version = "7.0~ynh6"

maintainers = ["Raoul de Limezy"]

[upstream]
license = "CC-BY-NC-SA-4.0"
website = "https://moncycle.app"
demo = "https://tableau.moncycle.app/connexion.php?email1=demo@moncycle.app&mdp=demo"
code = "https://github.com/jean-io/moncycle.app"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "100M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/moncycle"

    [install.init_main_permission]
    type = "group"

[resources]
        [resources.sources.main]
        url = "https://github.com/jean-io/moncycle.app/archive/4ee55999138825fd2f309fa27a69bafe6f5a0c36.zip"
        sha256 = "94c3010d12f9650ea87aecde046ef0ba4102308b566de94868adc76c69c22ccf"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.2-gd, php8.2-mysql, php8.2-mbstring"

    [resources.database]
    type = "mysql"
